http:
  host: "localhost"
  port: "8080"
grpc:
  address: ":50053"
postgres:
  user: "kare"
  password: "pass"
  address: "localhost:5431"
  dbname: "postgres"
  sslmode: "disable"
meeting:
  max_count_connections: 4
webrtc:
  stun: "stun:127.0.0.1:3478"
  turn: "turn:127.0.0.1:3478"
  username: "username"
  credential: "password"
  audio_codec: "audio/G.711"
  video_codec: "video/VP8"